- name: Install Nginx (Alpine)
  apk:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure web root exists
  file:
    path: "{{ document_root }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0755'

- name: Deploy index.html
  copy:
    src: index.html
    dest: "{{ document_root }}/index.html"
    owner: nginx
    group: nginx
    mode: '0644'

- name: Deploy nginx config
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/http.d/default.conf
  notify: restart nginx

- name: Enable nginx service
  service:
    name: nginx
    enabled: yes

- name: Start nginx service
  service:
    name: nginx
    state: started